"""empty message

Revision ID: 42581d149cc7
Revises: 
Create Date: 2019-07-16 15:23:43.977422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42581d149cc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('reply', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('answer_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'form_id', 'field_id', name='answer_pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    # ### end Alembic commands ###
